# Generated by Django 6.0 on 2026-01-27 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_add_company_visit'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyVisit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_by', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_visit',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['user', '-visited_at'], name='company_vis_user_id_522e5f_idx'), models.Index(fields=['company', '-visited_at'], name='company_vis_company_e250c0_idx')],
            },
        ),
    ]
