# Generated by Django 6.0 on 2026-01-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_company_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvisit',
            name='visited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
