# Generated by Django 6.0.1 on 2026-01-17 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('induty_code', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'industry',
            },
        ),
        migrations.CreateModel(
            name='IndustryRanking',
            fields=[
                ('ranking_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('base_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('industry', models.ForeignKey(db_column='industry_id', on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='industries.industry')),
            ],
            options={
                'db_table': 'industry_ranking',
            },
        ),
    ]
