# Generated by Django 6.0.1 on 2026-01-18 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('induty_code', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'industry',
            },
        ),
        migrations.CreateModel(
            name='KisIndustry',
            fields=[
                ('kis_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kis_industry',
            },
        ),
        migrations.CreateModel(
            name='KsicCategory',
            fields=[
                ('ksic_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ksic_category',
            },
        ),
        migrations.CreateModel(
            name='IndustryRanking',
            fields=[
                ('ranking_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('base_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('industry', models.ForeignKey(db_column='industry_id', on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='industries.industry')),
            ],
            options={
                'db_table': 'industry_ranking',
            },
        ),
        migrations.CreateModel(
            name='IndustryChart1d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.DateField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('change_value', models.FloatField(blank=True, null=True)),
                ('change_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.industry')),
            ],
            options={
                'db_table': 'industry_chart_1d',
                'ordering': ['industry', '-base_date'],
                'indexes': [models.Index(fields=['industry', '-base_date'], name='industry_ch_industr_57971d_idx')],
                'unique_together': {('industry', 'base_date')},
            },
        ),
        migrations.CreateModel(
            name='IndustryChart1w',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.DateField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('change_value', models.FloatField(blank=True, null=True)),
                ('change_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.industry')),
            ],
            options={
                'db_table': 'industry_chart_1w',
                'ordering': ['industry', '-base_date'],
                'indexes': [models.Index(fields=['industry', '-base_date'], name='industry_ch_industr_dde35f_idx')],
                'unique_together': {('industry', 'base_date')},
            },
        ),
        migrations.CreateModel(
            name='IndustryChart2w',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.DateField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('change_value', models.FloatField(blank=True, null=True)),
                ('change_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.industry')),
            ],
            options={
                'db_table': 'industry_chart_2w',
                'ordering': ['industry', '-base_date'],
                'indexes': [models.Index(fields=['industry', '-base_date'], name='industry_ch_industr_5e92ab_idx')],
                'unique_together': {('industry', 'base_date')},
            },
        ),
        migrations.CreateModel(
            name='IndustryChart3d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.DateField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('change_value', models.FloatField(blank=True, null=True)),
                ('change_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.industry')),
            ],
            options={
                'db_table': 'industry_chart_3d',
                'ordering': ['industry', '-base_date'],
                'indexes': [models.Index(fields=['industry', '-base_date'], name='industry_ch_industr_ea784b_idx')],
                'unique_together': {('industry', 'base_date')},
            },
        ),
        migrations.CreateModel(
            name='IndustryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=6)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='industries.kisindustry')),
            ],
            options={
                'db_table': 'industry_mapping',
                'unique_together': {('ticker', 'kis')},
            },
        ),
    ]
