# Generated by Django 6.0 on 2026-01-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['display_order', 'kis_code'], 'verbose_name': '산업', 'verbose_name_plural': '산업 목록'},
        ),
        migrations.AddField(
            model_name='industry',
            name='display_order',
            field=models.IntegerField(default=0, help_text='UI에서 정렬 시 사용', verbose_name='표시 순서'),
        ),
        migrations.AddField(
            model_name='industry',
            name='kis_code',
            field=models.CharField(blank=True, db_index=True, help_text='한국투자증권 업종 지수 코드 (예: 0013=전기전자)', max_length=4, null=True, verbose_name='KIS 업종 코드'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='induty_code',
            field=models.CharField(blank=True, db_index=True, help_text='kis_code로 대체됨. 마이그레이션 완료 후 제거 예정', max_length=20, null=True, unique=True, verbose_name='[DEPRECATED] 업종코드'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=255, verbose_name='산업명'),
        ),
    ]
