# Generated by Django 6.0.1 on 2026-01-15 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='induty_code',
        ),
        migrations.CreateModel(
            name='IndustryRanking',
            fields=[
                ('ranking_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('base_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('industry', models.ForeignKey(db_column='industry_id', on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='industries.industry')),
            ],
            options={
                'db_table': 'industry_ranking',
            },
        ),
    ]
