# Generated by Django 6.0.1 on 2026-01-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0002_remove_industry_induty_code_industryranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='induty_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
