# Generated by Django 6.0.1 on 2026-01-15 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0003_industry_induty_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryIndexHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_value', models.FloatField()),
                ('change_value', models.FloatField()),
                ('change_rate', models.FloatField()),
                ('base_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_history', to='industries.industry')),
            ],
            options={
                'db_table': 'industry_index_history',
                'ordering': ['base_date'],
                'unique_together': {('industry', 'base_date')},
            },
        ),
    ]
