# Generated by Django 6.0.1 on 2026-01-16 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0004_industryindexhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industryindexhistory',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='industryindexhistory',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='IndustryChart2Weekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.DateField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('change_value', models.FloatField(blank=True, null=True)),
                ('change_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.industry')),
            ],
            options={
                'db_table': 'industry_chart_2weekly',
                'ordering': ['base_date'],
                'indexes': [models.Index(fields=['industry', '-base_date'], name='industry_ch_industr_b22d5b_idx')],
                'unique_together': {('industry', 'base_date')},
            },
        ),
        migrations.CreateModel(
            name='IndustryChart3Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.DateField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('change_value', models.FloatField(blank=True, null=True)),
                ('change_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.industry')),
            ],
            options={
                'db_table': 'industry_chart_3day',
                'ordering': ['-base_date'],
                'indexes': [models.Index(fields=['industry', '-base_date'], name='industry_ch_industr_5c7007_idx')],
                'unique_together': {('industry', 'base_date')},
            },
        ),
        migrations.CreateModel(
            name='IndustryChartDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.DateField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('change_value', models.FloatField(blank=True, null=True)),
                ('change_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.industry')),
            ],
            options={
                'db_table': 'industry_chart_daily',
                'ordering': ['-base_date'],
                'indexes': [models.Index(fields=['industry', '-base_date'], name='industry_ch_industr_a1a005_idx')],
                'unique_together': {('industry', 'base_date')},
            },
        ),
        migrations.CreateModel(
            name='IndustryChartWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.DateField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('change_value', models.FloatField(blank=True, null=True)),
                ('change_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.industry')),
            ],
            options={
                'db_table': 'industry_chart_weekly',
                'ordering': ['-base_date'],
                'indexes': [models.Index(fields=['industry', '-base_date'], name='industry_ch_industr_4dfcb2_idx')],
                'unique_together': {('industry', 'base_date')},
            },
        ),
    ]
