# Generated by Django 6.0.1 on 2026-01-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0005_alter_industryindexhistory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndustryChart3Day',
            new_name='IndustryChart1d',
        ),
        migrations.RenameModel(
            old_name='IndustryChartWeekly',
            new_name='IndustryChart1w',
        ),
        migrations.RenameModel(
            old_name='IndustryChart2Weekly',
            new_name='IndustryChart2w',
        ),
        migrations.RenameModel(
            old_name='IndustryChartDaily',
            new_name='IndustryChart3d',
        ),
        migrations.RenameIndex(
            model_name='industrychart1d',
            new_name='industry_ch_industr_57971d_idx',
            old_name='industry_ch_industr_5c7007_idx',
        ),
        migrations.RenameIndex(
            model_name='industrychart1w',
            new_name='industry_ch_industr_dde35f_idx',
            old_name='industry_ch_industr_4dfcb2_idx',
        ),
        migrations.RenameIndex(
            model_name='industrychart2w',
            new_name='industry_ch_industr_5e92ab_idx',
            old_name='industry_ch_industr_b22d5b_idx',
        ),
        migrations.RenameIndex(
            model_name='industrychart3d',
            new_name='industry_ch_industr_ea784b_idx',
            old_name='industry_ch_industr_a1a005_idx',
        ),
        migrations.AlterModelTable(
            name='industrychart1d',
            table='industry_chart_1d',
        ),
        migrations.AlterModelTable(
            name='industrychart1w',
            table='industry_chart_1w',
        ),
        migrations.AlterModelTable(
            name='industrychart2w',
            table='industry_chart_2w',
        ),
        migrations.AlterModelTable(
            name='industrychart3d',
            table='industry_chart_3d',
        ),
    ]
