# Generated by Django 6.0.1 on 2026-01-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0006_rename_industrychart3day_industrychart1d_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrychart2w',
            options={'ordering': ['-base_date']},
        ),
        migrations.DeleteModel(
            name='IndustryIndexHistory',
        ),
    ]
