# Generated by Django 6.0.1 on 2026-01-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0007_alter_industrychart2w_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrychart1d',
            options={'ordering': ['industry', '-base_date']},
        ),
        migrations.AlterModelOptions(
            name='industrychart1w',
            options={'ordering': ['industry', '-base_date']},
        ),
        migrations.AlterModelOptions(
            name='industrychart2w',
            options={'ordering': ['industry', '-base_date']},
        ),
        migrations.AlterModelOptions(
            name='industrychart3d',
            options={'ordering': ['industry', '-base_date']},
        ),
    ]
