# Generated by Django 6.0.1 on 2026-01-17 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0008_alter_industrychart1d_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KisIndustry',
            fields=[
                ('kis_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KsicCategory',
            fields=[
                ('ksic_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('kis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.kisindustry')),
                ('ksic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.ksiccategory')),
            ],
            options={
                'unique_together': {('ksic', 'kis')},
            },
        ),
    ]
