# Generated by Django 6.0.1 on 2026-01-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0009_kisindustry_ksiccategory_industrymapping'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='industrymapping',
            table='industry_mapping',
        ),
    ]
