# Generated by Django 6.0.1 on 2026-01-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0010_alter_industrymapping_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kisindustry',
            table='kis_industry',
        ),
        migrations.AlterModelTable(
            name='ksiccategory',
            table='ksic_category',
        ),
    ]
