# Generated by Django 6.0 on 2026-01-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(help_text='검색 키워드 리스트', verbose_name='검색 키워드')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('running', '실행 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Celery 작업 ID')),
                ('total_articles', models.IntegerField(default=0, verbose_name='총 기사 수')),
                ('successful_articles', models.IntegerField(default=0, verbose_name='성공한 기사 수')),
                ('failed_articles', models.IntegerField(default=0, verbose_name='실패한 기사 수')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성 시간')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시간')),
            ],
            options={
                'verbose_name': '크롤링 작업',
                'verbose_name_plural': '크롤링 작업 목록',
                'db_table': 'crawl_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='crawl_jobs_created_67a21d_idx')],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='뉴스 ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('url', models.CharField(max_length=500, unique=True, verbose_name='링크')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='요약')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='발행일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정 시간')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '뉴스',
                'verbose_name_plural': '뉴스 목록',
                'db_table': 'news',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at', 'is_deleted'], name='news_publish_d5f2b2_idx'), models.Index(fields=['is_deleted', '-created_at'], name='news_is_dele_320b58_idx')],
            },
        ),
    ]
