# Generated by Django 6.0.1 on 2026-01-18 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(help_text='검색 키워드 리스트', verbose_name='검색 키워드')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('running', '실행 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Celery 작업 ID')),
                ('total_articles', models.IntegerField(default=0, verbose_name='총 기사 수')),
                ('successful_articles', models.IntegerField(default=0, verbose_name='성공한 기사 수')),
                ('failed_articles', models.IntegerField(default=0, verbose_name='실패한 기사 수')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성 시간')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시간')),
            ],
            options={
                'verbose_name': '크롤링 작업',
                'verbose_name_plural': '크롤링 작업 목록',
                'db_table': 'crawl_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='crawl_jobs_created_67a21d_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeywordFrequency',
            fields=[
                ('keyword_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='키워드 ID')),
                ('keyword', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='키워드')),
                ('frequency', models.IntegerField(default=0, verbose_name='전체 빈도수')),
                ('doc_count', models.IntegerField(default=0, verbose_name='문서 수')),
                ('first_seen_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='최초 등장일')),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='최종 등장일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '키워드 빈도수',
                'verbose_name_plural': '키워드 빈도수 목록',
                'db_table': 'keyword_frequencies',
                'ordering': ['-frequency', '-doc_count'],
                'indexes': [models.Index(fields=['-frequency', '-doc_count'], name='keyword_fre_frequen_5ebed9_idx'), models.Index(fields=['-last_seen_at'], name='keyword_fre_last_se_8e63d3_idx'), models.Index(fields=['keyword'], name='keyword_fre_keyword_5503b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='뉴스 ID')),
                ('title', models.CharField(max_length=500, verbose_name='제목')),
                ('url', models.CharField(max_length=1000, unique=True, verbose_name='링크')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='요약')),
                ('content', models.TextField(blank=True, null=True, verbose_name='정제된 본문')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='저자/기자')),
                ('press', models.CharField(blank=True, max_length=100, null=True, verbose_name='언론사')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='키워드 목록')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='발행일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정 시간')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '뉴스',
                'verbose_name_plural': '뉴스 목록',
                'db_table': 'news',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at', 'is_deleted'], name='news_publish_d5f2b2_idx'), models.Index(fields=['is_deleted', '-created_at'], name='news_is_dele_320b58_idx'), models.Index(fields=['press', '-published_at'], name='news_press_ffae02_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyNews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('company', models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, related_name='company_news', to='companies.company', verbose_name='기업')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_mappings', to='news.news', verbose_name='뉴스')),
            ],
            options={
                'verbose_name': '기업 뉴스 매핑',
                'verbose_name_plural': '기업 뉴스 매핑 목록',
                'db_table': 'company_news',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='company_new_stock_c_c8e5d4_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'news'), name='unique_company_news_mapping')],
            },
        ),
    ]
