# Generated by Django 6.0.1 on 2026-01-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordfrequency',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='최초 등장일'),
        ),
        migrations.AlterField(
            model_name='keywordfrequency',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='최종 등장일'),
        ),
    ]
