# Generated by Django 6.0.1 on 2026-01-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # ============================================
        # 0. TimescaleDB Extension 설치
        # ============================================
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS timescaledb;",
            reverse_sql="DROP EXTENSION IF EXISTS timescaledb CASCADE;",
        ),
        # ============================================
        # 1. stock_ticks 테이블 생성 (TimescaleDB Hypertable)
        # ============================================
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS stock_ticks (
                stock_code VARCHAR(10) NOT NULL,
                symbol VARCHAR(10),
                time TIMESTAMPTZ NOT NULL,
                price DECIMAL(12, 2) NOT NULL,
                volume BIGINT NOT NULL,
                PRIMARY KEY (stock_code, time)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS stock_ticks CASCADE;",
        ),
        # Hypertable 변환 (TimescaleDB 필수)
        migrations.RunSQL(
            """
            SELECT create_hypertable(
                'stock_ticks',
                'time',
                if_not_exists => TRUE,
                chunk_time_interval => INTERVAL '1 day'
            );
            """,
            reverse_sql="",  # Hypertable은 테이블 삭제 시 자동 정리
        ),
        # stock_ticks 인덱스
        migrations.RunSQL(
            """
            CREATE INDEX IF NOT EXISTS idx_stock_ticks_code_time
                ON stock_ticks (stock_code, time DESC);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_stock_ticks_code_time;",
        ),
        # ============================================
        # 2. 통합 OHLCV 테이블들
        # ============================================
        # 1분봉 테이블 생성 (id 컬럼 포함, 복합 UNIQUE 제약조건)
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS stock_prices_1m (
                id BIGSERIAL PRIMARY KEY,
                bucket TIMESTAMPTZ NOT NULL,
                stock_code VARCHAR(10) NOT NULL,
                open DECIMAL(12, 2),
                high DECIMAL(12, 2),
                low DECIMAL(12, 2),
                close DECIMAL(12, 2),
                volume BIGINT,
                amount DECIMAL(20, 2),
                trade_count INTEGER DEFAULT 0,
                source VARCHAR(20) DEFAULT 'realtime',
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (stock_code, bucket)
            );
            CREATE INDEX IF NOT EXISTS idx_prices_1m_bucket ON stock_prices_1m(bucket DESC);
            """,
            reverse_sql="DROP TABLE IF EXISTS stock_prices_1m CASCADE;",
        ),
        # 15분봉 테이블 생성 (id 컬럼 포함, 복합 UNIQUE 제약조건)
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS stock_prices_15m (
                id BIGSERIAL PRIMARY KEY,
                bucket TIMESTAMPTZ NOT NULL,
                stock_code VARCHAR(10) NOT NULL,
                open DECIMAL(12, 2),
                high DECIMAL(12, 2),
                low DECIMAL(12, 2),
                close DECIMAL(12, 2),
                volume BIGINT,
                amount DECIMAL(20, 2),
                trade_count INTEGER DEFAULT 0,
                source VARCHAR(20) DEFAULT 'realtime',
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (stock_code, bucket)
            );
            CREATE INDEX IF NOT EXISTS idx_prices_15m_bucket ON stock_prices_15m(bucket DESC);
            """,
            reverse_sql="DROP TABLE IF EXISTS stock_prices_15m CASCADE;",
        ),
        # 1시간봉 테이블 생성 (id 컬럼 포함, 복합 UNIQUE 제약조건)
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS stock_prices_1h (
                id BIGSERIAL PRIMARY KEY,
                bucket TIMESTAMPTZ NOT NULL,
                stock_code VARCHAR(10) NOT NULL,
                open DECIMAL(12, 2),
                high DECIMAL(12, 2),
                low DECIMAL(12, 2),
                close DECIMAL(12, 2),
                volume BIGINT,
                amount DECIMAL(20, 2),
                trade_count INTEGER DEFAULT 0,
                source VARCHAR(20) DEFAULT 'realtime',
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (stock_code, bucket)
            );
            CREATE INDEX IF NOT EXISTS idx_prices_1h_bucket ON stock_prices_1h(bucket DESC);
            """,
            reverse_sql="DROP TABLE IF EXISTS stock_prices_1h CASCADE;",
        ),
        # 1일봉 테이블 생성 (id 컬럼 포함, 복합 UNIQUE 제약조건)
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS stock_prices_1d (
                id BIGSERIAL PRIMARY KEY,
                bucket TIMESTAMPTZ NOT NULL,
                stock_code VARCHAR(10) NOT NULL,
                open DECIMAL(12, 2),
                high DECIMAL(12, 2),
                low DECIMAL(12, 2),
                close DECIMAL(12, 2),
                volume BIGINT,
                amount DECIMAL(20, 2),
                trade_count INTEGER DEFAULT 0,
                source VARCHAR(20) DEFAULT 'realtime',
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (stock_code, bucket)
            );
            CREATE INDEX IF NOT EXISTS idx_prices_1d_bucket ON stock_prices_1d(bucket DESC);
            """,
            reverse_sql="DROP TABLE IF EXISTS stock_prices_1d CASCADE;",
        ),
        # Django 모델 정의 (managed=False로 Django가 테이블을 관리하지 않음)
        migrations.CreateModel(
            name="StockPrice15m",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket", models.DateTimeField(db_column="bucket")),
                ("stock_code", models.CharField(db_column="stock_code", max_length=10)),
                (
                    "open",
                    models.DecimalField(
                        db_column="open", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        db_column="high", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        db_column="low", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        db_column="close", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(db_column="volume", default=0)),
                (
                    "amount",
                    models.DecimalField(
                        db_column="amount", decimal_places=2, default=0, max_digits=20
                    ),
                ),
                (
                    "trade_count",
                    models.IntegerField(db_column="trade_count", default=0),
                ),
                (
                    "source",
                    models.CharField(
                        db_column="source", default="realtime", max_length=20
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
            ],
            options={
                "db_table": "stock_prices_15m",
                "ordering": ["-bucket"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StockPrice1d",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket", models.DateTimeField(db_column="bucket")),
                ("stock_code", models.CharField(db_column="stock_code", max_length=10)),
                (
                    "open",
                    models.DecimalField(
                        db_column="open", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        db_column="high", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        db_column="low", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        db_column="close", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(db_column="volume", default=0)),
                (
                    "amount",
                    models.DecimalField(
                        db_column="amount", decimal_places=2, default=0, max_digits=20
                    ),
                ),
                (
                    "trade_count",
                    models.IntegerField(db_column="trade_count", default=0),
                ),
                (
                    "source",
                    models.CharField(
                        db_column="source", default="realtime", max_length=20
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
            ],
            options={
                "db_table": "stock_prices_1d",
                "ordering": ["-bucket"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StockPrice1h",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket", models.DateTimeField(db_column="bucket")),
                ("stock_code", models.CharField(db_column="stock_code", max_length=10)),
                (
                    "open",
                    models.DecimalField(
                        db_column="open", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        db_column="high", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        db_column="low", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        db_column="close", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(db_column="volume", default=0)),
                (
                    "amount",
                    models.DecimalField(
                        db_column="amount", decimal_places=2, default=0, max_digits=20
                    ),
                ),
                (
                    "trade_count",
                    models.IntegerField(db_column="trade_count", default=0),
                ),
                (
                    "source",
                    models.CharField(
                        db_column="source", default="realtime", max_length=20
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
            ],
            options={
                "db_table": "stock_prices_1h",
                "ordering": ["-bucket"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StockPrice1m",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket", models.DateTimeField(db_column="bucket")),
                ("stock_code", models.CharField(db_column="stock_code", max_length=10)),
                (
                    "open",
                    models.DecimalField(
                        db_column="open", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        db_column="high", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        db_column="low", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        db_column="close", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(db_column="volume", default=0)),
                (
                    "amount",
                    models.DecimalField(
                        db_column="amount", decimal_places=2, default=0, max_digits=20
                    ),
                ),
                (
                    "trade_count",
                    models.IntegerField(db_column="trade_count", default=0),
                ),
                (
                    "source",
                    models.CharField(
                        db_column="source", default="realtime", max_length=20
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
            ],
            options={
                "db_table": "stock_prices_1m",
                "ordering": ["-bucket"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StockTick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_code", models.CharField(db_column="stock_code", max_length=10)),
                (
                    "symbol",
                    models.CharField(
                        blank=True, db_column="symbol", max_length=10, null=True
                    ),
                ),
                ("time", models.DateTimeField(db_column="time")),
                (
                    "price",
                    models.DecimalField(
                        db_column="price", decimal_places=2, max_digits=12
                    ),
                ),
                ("volume", models.BigIntegerField(db_column="volume")),
            ],
            options={
                "db_table": "stock_ticks",
                "ordering": ["-time"],
                "managed": False,
            },
        ),
        # ============================================
        # 3. Continuous Aggregates (TimescaleDB)
        # ============================================
        # 1분봉 Continuous Aggregate
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW IF NOT EXISTS _cagg_1m
            WITH (timescaledb.continuous) AS
            SELECT
                time_bucket('1 minute', time) AS bucket,
                stock_code,
                first(price, time) AS open,
                max(price) AS high,
                min(price) AS low,
                last(price, time) AS close,
                sum(volume) AS volume,
                sum(price * volume) AS amount,
                count(*) AS trade_count
            FROM stock_ticks
            GROUP BY bucket, stock_code
            WITH NO DATA;
            """,
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS _cagg_1m CASCADE;",
        ),
        # 15분봉 Continuous Aggregate
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW IF NOT EXISTS _cagg_15m
            WITH (timescaledb.continuous) AS
            SELECT
                time_bucket('15 minutes', time) AS bucket,
                stock_code,
                first(price, time) AS open,
                max(price) AS high,
                min(price) AS low,
                last(price, time) AS close,
                sum(volume) AS volume,
                sum(price * volume) AS amount,
                count(*) AS trade_count
            FROM stock_ticks
            GROUP BY bucket, stock_code
            WITH NO DATA;
            """,
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS _cagg_15m CASCADE;",
        ),
        # 1시간봉 Continuous Aggregate
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW IF NOT EXISTS _cagg_1h
            WITH (timescaledb.continuous) AS
            SELECT
                time_bucket('1 hour', time) AS bucket,
                stock_code,
                first(price, time) AS open,
                max(price) AS high,
                min(price) AS low,
                last(price, time) AS close,
                sum(volume) AS volume,
                sum(price * volume) AS amount,
                count(*) AS trade_count
            FROM stock_ticks
            GROUP BY bucket, stock_code
            WITH NO DATA;
            """,
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS _cagg_1h CASCADE;",
        ),
        # 1일봉 Continuous Aggregate
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW IF NOT EXISTS _cagg_1d
            WITH (timescaledb.continuous) AS
            SELECT
                time_bucket('1 day', time) AS bucket,
                stock_code,
                first(price, time) AS open,
                max(price) AS high,
                min(price) AS low,
                last(price, time) AS close,
                sum(volume) AS volume,
                sum(price * volume) AS amount,
                count(*) AS trade_count
            FROM stock_ticks
            GROUP BY bucket, stock_code
            WITH NO DATA;
            """,
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS _cagg_1d CASCADE;",
        ),
        # ============================================
        # 4. Continuous Aggregate 자동 새로고침 정책
        # ============================================
        migrations.RunSQL(
            """
            SELECT add_continuous_aggregate_policy('_cagg_1m',
                start_offset => INTERVAL '10 minutes',
                end_offset => INTERVAL '1 minute',
                schedule_interval => INTERVAL '30 seconds',
                if_not_exists => TRUE
            );
            """,
            reverse_sql="SELECT remove_continuous_aggregate_policy('_cagg_1m', if_exists => TRUE);",
        ),
        migrations.RunSQL(
            """
            SELECT add_continuous_aggregate_policy('_cagg_15m',
                start_offset => INTERVAL '1 hour',
                end_offset => INTERVAL '15 minutes',
                schedule_interval => INTERVAL '5 minutes',
                if_not_exists => TRUE
            );
            """,
            reverse_sql="SELECT remove_continuous_aggregate_policy('_cagg_15m', if_exists => TRUE);",
        ),
        migrations.RunSQL(
            """
            SELECT add_continuous_aggregate_policy('_cagg_1h',
                start_offset => INTERVAL '4 hours',
                end_offset => INTERVAL '1 hour',
                schedule_interval => INTERVAL '15 minutes',
                if_not_exists => TRUE
            );
            """,
            reverse_sql="SELECT remove_continuous_aggregate_policy('_cagg_1h', if_exists => TRUE);",
        ),
        migrations.RunSQL(
            """
            SELECT add_continuous_aggregate_policy('_cagg_1d',
                start_offset => INTERVAL '3 days',
                end_offset => INTERVAL '1 day',
                schedule_interval => INTERVAL '1 hour',
                if_not_exists => TRUE
            );
            """,
            reverse_sql="SELECT remove_continuous_aggregate_policy('_cagg_1d', if_exists => TRUE);",
        ),
    ]
