# Generated by Django 6.0.1 on 2026-01-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice15m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.DateTimeField(db_column='bucket')),
                ('stock_code', models.CharField(db_column='stock_code', max_length=10)),
                ('open', models.DecimalField(db_column='open', decimal_places=2, max_digits=12, null=True)),
                ('high', models.DecimalField(db_column='high', decimal_places=2, max_digits=12, null=True)),
                ('low', models.DecimalField(db_column='low', decimal_places=2, max_digits=12, null=True)),
                ('close', models.DecimalField(db_column='close', decimal_places=2, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(db_column='volume', default=0)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, default=0, max_digits=20)),
                ('trade_count', models.IntegerField(db_column='trade_count', default=0)),
                ('source', models.CharField(db_column='source', default='realtime', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'stock_prices_15m',
                'ordering': ['-bucket'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockPrice1d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.DateTimeField(db_column='bucket')),
                ('stock_code', models.CharField(db_column='stock_code', max_length=10)),
                ('open', models.DecimalField(db_column='open', decimal_places=2, max_digits=12, null=True)),
                ('high', models.DecimalField(db_column='high', decimal_places=2, max_digits=12, null=True)),
                ('low', models.DecimalField(db_column='low', decimal_places=2, max_digits=12, null=True)),
                ('close', models.DecimalField(db_column='close', decimal_places=2, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(db_column='volume', default=0)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, default=0, max_digits=20)),
                ('trade_count', models.IntegerField(db_column='trade_count', default=0)),
                ('source', models.CharField(db_column='source', default='realtime', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'stock_prices_1d',
                'ordering': ['-bucket'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockPrice1h',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.DateTimeField(db_column='bucket')),
                ('stock_code', models.CharField(db_column='stock_code', max_length=10)),
                ('open', models.DecimalField(db_column='open', decimal_places=2, max_digits=12, null=True)),
                ('high', models.DecimalField(db_column='high', decimal_places=2, max_digits=12, null=True)),
                ('low', models.DecimalField(db_column='low', decimal_places=2, max_digits=12, null=True)),
                ('close', models.DecimalField(db_column='close', decimal_places=2, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(db_column='volume', default=0)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, default=0, max_digits=20)),
                ('trade_count', models.IntegerField(db_column='trade_count', default=0)),
                ('source', models.CharField(db_column='source', default='realtime', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'stock_prices_1h',
                'ordering': ['-bucket'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockPrice1m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.DateTimeField(db_column='bucket')),
                ('stock_code', models.CharField(db_column='stock_code', max_length=10)),
                ('open', models.DecimalField(db_column='open', decimal_places=2, max_digits=12, null=True)),
                ('high', models.DecimalField(db_column='high', decimal_places=2, max_digits=12, null=True)),
                ('low', models.DecimalField(db_column='low', decimal_places=2, max_digits=12, null=True)),
                ('close', models.DecimalField(db_column='close', decimal_places=2, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(db_column='volume', default=0)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, default=0, max_digits=20)),
                ('trade_count', models.IntegerField(db_column='trade_count', default=0)),
                ('source', models.CharField(db_column='source', default='realtime', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'stock_prices_1m',
                'ordering': ['-bucket'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_column='stock_code', max_length=10)),
                ('symbol', models.CharField(blank=True, db_column='symbol', max_length=10, null=True)),
                ('time', models.DateTimeField(db_column='time')),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField(db_column='volume')),
            ],
            options={
                'db_table': 'stock_ticks',
                'ordering': ['-time'],
                'managed': False,
            },
        ),
    ]
