# Generated by Django 6.0 on 2026-01-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktick',
            options={'managed': False, 'ordering': ['-time']},
        ),
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> develop
