# Generated by Django 6.0.1 on 2026-01-19 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('comparison_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_comparison',
            },
        ),
        migrations.CreateModel(
            name='ComparisonCompany',
            fields=[
                ('comparison_company_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_items', to='comparisons.comparison')),
            ],
            options={
                'db_table': 'comparison_company',
                'unique_together': {('comparison', 'company')},
            },
        ),
    ]
