"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse
from datetime import timedelta
from dotenv import load_dotenv
from celery.schedules import crontab


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 파일 로드
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "daphne",  # Channels ASGI 서버 (INSTALLED_APPS 최상단)
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "channels",  # Django Channels
    # 만든 앱 등록
    "industries",
    "companies",
    "core",
    "news",
    "users",
]

# ASGI Application
ASGI_APPLICATION = "config.asgi.application"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Django API",
    "DESCRIPTION": "Django REST API with TimescaleDB, Redis, OpenSearch",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # API 문서 UI 설정
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,  # 딥 링킹 활성화
        "persistAuthorization": True,  # 인증 정보 유지
        "displayOperationId": True,  # Operation ID 표시
        "filter": True,  # 검색 필터 활성화
    },
    # 스키마 생성 설정
    "COMPONENT_SPLIT_REQUEST": True,  # 요청/응답 스키마 분리
    "SCHEMA_PATH_PREFIX": "/api/",  # API 경로 접두사
    # 태그 정렬
    "TAGS": [
        {"name": "Health Check", "description": "서버 상태 확인"},
        {"name": "Company", "description": "기업 정보 및 재무 데이터 조회"},
        {"name": "Industry", "description": "산업별 기업 정보 조회"},
    ],
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Parse DATABASE_URL or use environment variables
if os.getenv("DATABASE_URL"):
    db_url = urlparse(os.getenv("DATABASE_URL"))
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": db_url.path[1:],  # Remove leading '/'
            "USER": db_url.username,
            "PASSWORD": db_url.password,
            "HOST": db_url.hostname,
            "PORT": db_url.port or 5432,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "postgres"),
            "USER": os.getenv("POSTGRES_USER", "postgres"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
            "HOST": os.getenv("POSTGRES_HOST", "localhost"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }

# Redis Cache Configuration
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
    }
}

# Redis Session Configuration (optional)
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# OpenSearch Configuration
OPENSEARCH_HOST = os.getenv("OPENSEARCH_HOST", "localhost:9200")
OPENSEARCH_USE_SSL = os.getenv("OPENSEARCH_USE_SSL", "false").lower() == "true"
OPENSEARCH_VERIFY_CERTS = (
    os.getenv("OPENSEARCH_VERIFY_CERTS", "false").lower() == "true"
)

# Redis Channel Configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}

# Celery Configuration
# Docker 환경에서는 redis 호스트명 사용, 로컬에서는 localhost 사용
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://redis:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Seoul"
CELERY_ENABLE_UTC = False
# Celery 6.0+ 호환성을 위한 설정
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# =============================================================================
# 배치 작업 활성화 설정 (개발 환경에서 토큰 사용 절감)
# =============================================================================
# 환경변수로 개별 배치 작업을 활성화/비활성화할 수 있습니다.
# 기본값은 모두 비활성화 (개발 환경 기본)
# 프로덕션에서는 .env 파일에서 true로 설정하세요.

# 뉴스 크롤링 배치 (Gemini 토큰 사용: 정제, 요약, 임베딩)
NEWS_BATCH_ENABLED = os.getenv("NEWS_BATCH_ENABLED", "false").lower() == "true"

# DART 동기화 배치 (DART OpenAPI - 무료, 기본 활성화)
DART_SYNC_ENABLED = os.getenv("DART_SYNC_ENABLED", "true").lower() == "true"

# 보고서 처리 배치 (Gemini 토큰 사용: 정제, 정보추출, 임베딩)
REPORT_PROCESSING_ENABLED = (
    os.getenv("REPORT_PROCESSING_ENABLED", "false").lower() == "true"
)

# =============================================================================
# Celery Beat Schedule (주기적 작업 스케줄링)
# =============================================================================
# 배치 작업은 위의 활성화 설정에 따라 조건부로 등록됩니다.

CELERY_BEAT_SCHEDULE = {}

# 뉴스 크롤링: 매 3시간마다 실행
if NEWS_BATCH_ENABLED:
    CELERY_BEAT_SCHEDULE["crawl-news-every-3-hours"] = {
        "task": "news.tasks.workflows.scheduled_crawl_news",
        "schedule": 3 * 60 * 60,  # 3시간 (초 단위)
        "kwargs": {
            "keywords": [
                "경제",
                "증권",
                "기업",
                "IT",
                "기술",
                "산업",
                "무역",
                "금융",
            ],
            "max_articles_per_keyword": 10,
        },
    }

# DART 기업 정보 동기화: 주 1회 (일요일 새벽 3시)
if DART_SYNC_ENABLED:
    CELERY_BEAT_SCHEDULE["sync-dart-company-info-weekly"] = {
        "task": "companies.tasks.dart_sync.sync_all_company_info",
        "schedule": crontab(day_of_week=0, hour=3, minute=0),
    }
    # DART 보고서 목록 동기화: 일 1회 (새벽 4시)
    CELERY_BEAT_SCHEDULE["sync-dart-reports-daily"] = {
        "task": "companies.tasks.dart_sync.sync_all_reports",
        "schedule": crontab(hour=4, minute=0),
    }
    # 시가총액 갱신: 평일 장 마감 후 (16:10)
    # KIS REST API를 통해 전체 기업의 시가총액 배치 갱신
    CELERY_BEAT_SCHEDULE["sync-market-amount-daily"] = {
        "task": "companies.tasks.kis_market_amount.sync_all_market_amount",
        "schedule": crontab(day_of_week="1-5", hour=16, minute=10),
    }

# =============================================================================
# 주가 데이터 동기화 스케줄 (Continuous Aggregate → 통합 테이블)
# =============================================================================
# 장중(09:00~15:30)에만 실행되도록 설정
STOCK_PRICE_SYNC_ENABLED = (
    os.getenv("STOCK_PRICE_SYNC_ENABLED", "true").lower() == "true"
)

if STOCK_PRICE_SYNC_ENABLED:
    # 1분봉: 30초마다 동기화
    CELERY_BEAT_SCHEDULE["sync-stock-prices-1m"] = {
        "task": "core.tasks.price_sync.sync_cagg_to_prices_1m",
        "schedule": 30.0,  # 30초
    }
    # 15분봉: 5분마다 동기화
    CELERY_BEAT_SCHEDULE["sync-stock-prices-15m"] = {
        "task": "core.tasks.price_sync.sync_cagg_to_prices_15m",
        "schedule": crontab(minute="*/5"),
    }
    # 1시간봉: 15분마다 동기화
    CELERY_BEAT_SCHEDULE["sync-stock-prices-1h"] = {
        "task": "core.tasks.price_sync.sync_cagg_to_prices_1h",
        "schedule": crontab(minute="*/15"),
    }
    # 1일봉: 1시간마다 동기화
    CELERY_BEAT_SCHEDULE["sync-stock-prices-1d"] = {
        "task": "core.tasks.price_sync.sync_cagg_to_prices_1d",
        "schedule": crontab(minute=0),
    }

# API Keys
# 필수 API 키: 빈 문자열도 None으로 처리하여 명시적 검증 가능하도록 함
NAVER_CLIENT_ID = os.getenv("NAVER_CLIENT_ID") or None
NAVER_CLIENT_SECRET = os.getenv("NAVER_CLIENT_SECRET") or None
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY") or None
# 선택 API 키: Jina는 무료 티어로도 동작 가능
JINA_API_KEY = os.getenv("JINA_API_KEY") or None
DART_API_KEY = os.getenv("DART_API_KEY") or None

# Logo.dev API (기업 로고 이미지)
# 무료 tier: 월 50만 요청 (attribution 필요)
LOGO_DEV_PUB_KEY = os.getenv("LOGO_DEV_PUB_KEY") or None

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_TZ = True

USE_I18N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

JWT_SIGNING_KEY = os.getenv("JWT_SIGNING_KEY", SECRET_KEY)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": JWT_SIGNING_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

AUTHENTICATION_BACKENDS = [
    "users.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]
# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
