# Generated by Django 6.0 on 2026-01-13 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "stock_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("corp_code", models.CharField(max_length=8, null=True, unique=True)),
                (
                    "induty_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("logo_url", models.URLField(blank=True, max_length=500, null=True)),
                ("market_amount", models.BigIntegerField(default=0)),
                ("ceo_name", models.CharField(blank=True, max_length=100, null=True)),
                ("establishment_date", models.DateField(null=True)),
                (
                    "homepage_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rcept_no", models.CharField(max_length=20, unique=True)),
                ("report_name", models.CharField(max_length=500)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("A", "정기공시"),
                            ("B", "주요사항보고"),
                            ("C", "발행공시"),
                            ("D", "지분공시"),
                            ("E", "기타공시"),
                            ("F", "외부감사관련"),
                            ("G", "펀드공시"),
                            ("H", "자산유동화"),
                            ("I", "거래소공시"),
                            ("J", "공정위공시"),
                        ],
                        max_length=1,
                    ),
                ),
                ("submitted_at", models.DateField()),
                ("report_url", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="companies.company",
                        to_field="stock_code",
                        db_column="company_id",
                    ),
                ),
            ],
            options={
                "db_table": "report",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="RevenueComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField()),
                ("segment_name", models.CharField(max_length=255)),
                ("revenue", models.BigIntegerField()),
                (
                    "ratio",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_compositions",
                        to="companies.company",
                        to_field="stock_code",
                        db_column="company_id",
                    ),
                ),
            ],
            options={
                "db_table": "revenue_composition",
                "ordering": ["-fiscal_year", "-revenue"],
            },
        ),
        migrations.CreateModel(
            name="FinancialStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField()),
                ("report_code", models.CharField(max_length=5)),
                ("revenue", models.BigIntegerField(null=True)),
                ("operating_profit", models.BigIntegerField(null=True)),
                ("net_income", models.BigIntegerField(null=True)),
                ("total_assets", models.BigIntegerField(null=True)),
                ("total_liabilities", models.BigIntegerField(null=True)),
                ("total_equity", models.BigIntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_statements",
                        to="companies.company",
                        to_field="stock_code",
                        db_column="company_id",
                    ),
                ),
            ],
            options={
                "db_table": "financial_statement",
                "ordering": ["-fiscal_year", "-report_code"],
                "unique_together": {("company", "fiscal_year", "report_code")},
            },
        ),
    ]
