# Generated by Django 6.0.1 on 2026-01-19 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('stock_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('corp_code', models.CharField(max_length=8, null=True, unique=True)),
                ('induty_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('market', models.CharField(blank=True, choices=[('KOSPI', '유가증권'), ('KOSDAQ', '코스닥')], db_index=True, max_length=10, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('market_amount', models.BigIntegerField(default=0)),
                ('ceo_name', models.CharField(blank=True, max_length=100, null=True)),
                ('establishment_date', models.DateField(null=True)),
                ('homepage_url', models.URLField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('last_info_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 정보 동기화 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('industry', models.ForeignKey(blank=True, db_column='industry_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='industries.industry')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='CompanyRanking',
            fields=[
                ('ranking_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('base_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('stock_code', models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='companies.company')),
            ],
            options={
                'db_table': 'company_ranking',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcept_no', models.CharField(max_length=20, unique=True)),
                ('report_name', models.CharField(max_length=500)),
                ('report_type', models.CharField(choices=[('A', '정기공시'), ('B', '주요사항보고'), ('C', '발행공시'), ('D', '지분공시'), ('E', '기타공시'), ('F', '외부감사관련'), ('G', '펀드공시'), ('H', '자산유동화'), ('I', '거래소공시'), ('J', '공정위공시')], max_length=1)),
                ('submitted_at', models.DateField()),
                ('report_url', models.URLField(max_length=500)),
                ('raw_content', models.TextField(blank=True, null=True, verbose_name='원본 본문')),
                ('refined_content', models.TextField(blank=True, null=True, verbose_name='정제된 본문')),
                ('extracted_info', models.JSONField(blank=True, null=True, verbose_name='구조화된 추출 정보')),
                ('embedding', models.JSONField(blank=True, null=True, verbose_name='벡터 임베딩')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 완료 시간')),
                ('processing_status', models.CharField(choices=[('pending', '대기'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.company')),
            ],
            options={
                'db_table': 'report',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('segment_name', models.CharField(max_length=255)),
                ('revenue', models.BigIntegerField()),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='revenue_compositions', to='companies.company')),
            ],
            options={
                'db_table': 'revenue_composition',
                'ordering': ['-fiscal_year', '-revenue'],
            },
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(verbose_name='배당 기준 연도')),
                ('dividend_per_share', models.DecimalField(decimal_places=2, help_text='단위: 원', max_digits=10, verbose_name='주당 배당금')),
                ('dividend_type', models.CharField(choices=[('cash', '현금배당'), ('stock', '주식배당')], default='cash', max_length=20, verbose_name='배당 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='companies.company')),
            ],
            options={
                'db_table': 'dividend',
                'ordering': ['-fiscal_year'],
                'unique_together': {('company', 'fiscal_year', 'dividend_type')},
            },
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('report_code', models.CharField(max_length=5)),
                ('revenue', models.BigIntegerField(null=True)),
                ('operating_profit', models.BigIntegerField(null=True)),
                ('net_income', models.BigIntegerField(null=True)),
                ('total_assets', models.BigIntegerField(null=True)),
                ('total_liabilities', models.BigIntegerField(null=True)),
                ('total_equity', models.BigIntegerField(null=True)),
                ('per', models.DecimalField(blank=True, decimal_places=2, help_text='시가총액 ÷ 당기순이익', max_digits=10, null=True, verbose_name='PER (주가수익비율)')),
                ('pbr', models.DecimalField(blank=True, decimal_places=2, help_text='시가총액 ÷ 총자본', max_digits=10, null=True, verbose_name='PBR (주가순자산비율)')),
                ('roe', models.DecimalField(blank=True, decimal_places=2, help_text='(당기순이익 ÷ 총자본) × 100', max_digits=10, null=True, verbose_name='ROE (자기자본이익률)')),
                ('debt_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='(총부채 ÷ 총자본) × 100', max_digits=10, null=True, verbose_name='부채비율')),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=2, help_text='(연간 배당금 ÷ 현재 주가) × 100', max_digits=10, null=True, verbose_name='배당수익률')),
                ('eps', models.DecimalField(blank=True, decimal_places=2, help_text='당기순이익 ÷ 발행주식수', max_digits=15, null=True, verbose_name='EPS (주당순이익)')),
                ('operating_profit_margin', models.DecimalField(blank=True, decimal_places=2, help_text='(영업이익 ÷ 매출액) × 100', max_digits=10, null=True, verbose_name='영업이익률')),
                ('yoy_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='전년 대비 매출액 성장률 (%)', max_digits=10, null=True, verbose_name='매출액 YoY')),
                ('yoy_operating_profit', models.DecimalField(blank=True, decimal_places=2, help_text='전년 대비 영업이익 성장률 (%)', max_digits=10, null=True, verbose_name='영업이익 YoY')),
                ('yoy_net_income', models.DecimalField(blank=True, decimal_places=2, help_text='전년 대비 당기순이익 성장률 (%)', max_digits=10, null=True, verbose_name='당기순이익 YoY')),
                ('metrics_calculated_at', models.DateTimeField(blank=True, help_text='마지막으로 재무 지표를 계산한 시간', null=True, verbose_name='지표 계산 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='companies.company')),
            ],
            options={
                'db_table': 'financial_statement',
                'ordering': ['-fiscal_year', '-report_code'],
                'unique_together': {('company', 'fiscal_year', 'report_code')},
            },
        ),
    ]
