# Generated by Django 6.0 on 2026-01-14 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='embedding',
            field=models.JSONField(blank=True, null=True, verbose_name='벡터 임베딩'),
        ),
        migrations.AddField(
            model_name='report',
            name='extracted_info',
            field=models.JSONField(blank=True, null=True, verbose_name='구조화된 추출 정보'),
        ),
        migrations.AddField(
            model_name='report',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='처리 완료 시간'),
        ),
        migrations.AddField(
            model_name='report',
            name='processing_status',
            field=models.CharField(choices=[('pending', '대기'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='처리 상태'),
        ),
        migrations.AddField(
            model_name='report',
            name='raw_content',
            field=models.TextField(blank=True, null=True, verbose_name='원본 본문'),
        ),
        migrations.AddField(
            model_name='report',
            name='refined_content',
            field=models.TextField(blank=True, null=True, verbose_name='정제된 본문'),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='report',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='revenuecomposition',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='revenue_compositions', to='companies.company'),
        ),
    ]
