# Generated by Django 6.0 on 2026-01-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_info_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 정보 동기화 시간'),
        ),
    ]
