# Generated by Django 6.0.1 on 2026-01-15 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('industries', '0004_industryindexhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, db_column='industry_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='industries.industry'),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='report',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='revenuecomposition',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='revenue_compositions', to='companies.company'),
        ),
    ]
