# Generated by Django 6.0 on 2026-01-18 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='debt_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(총부채 ÷ 총자본) × 100', max_digits=10, null=True, verbose_name='부채비율'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(연간 배당금 ÷ 현재 주가) × 100', max_digits=10, null=True, verbose_name='배당수익률'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='metrics_calculated_at',
            field=models.DateTimeField(blank=True, help_text='마지막으로 재무 지표를 계산한 시간', null=True, verbose_name='지표 계산 시간'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='pbr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='시가총액 ÷ 총자본', max_digits=10, null=True, verbose_name='PBR (주가순자산비율)'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='per',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='시가총액 ÷ 당기순이익', max_digits=10, null=True, verbose_name='PER (주가수익비율)'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='roe',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(당기순이익 ÷ 총자본) × 100', max_digits=10, null=True, verbose_name='ROE (자기자본이익률)'),
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(verbose_name='배당 기준 연도')),
                ('dividend_per_share', models.DecimalField(decimal_places=2, help_text='단위: 원', max_digits=10, verbose_name='주당 배당금')),
                ('dividend_type', models.CharField(choices=[('cash', '현금배당'), ('stock', '주식배당')], default='cash', max_length=20, verbose_name='배당 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='companies.company')),
            ],
            options={
                'db_table': 'dividend',
                'ordering': ['-fiscal_year'],
                'unique_together': {('company', 'fiscal_year', 'dividend_type')},
            },
        ),
    ]
