# Generated by Django 6.0 on 2026-01-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_sankeydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='original_ksic_code',
            field=models.CharField(blank=True, db_index=True, help_text='DART API에서 가져온 원본 업종코드 (KIS 변환 전)', max_length=20, null=True, verbose_name='원본 KSIC 코드'),
        ),
    ]
