# Generated by Django 6.0.1 on 2026-01-15 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_report_embedding_report_extracted_info_and_more'),
        ('industries', '0002_remove_industry_induty_code_industryranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, db_column='industry_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='industries.industry'),
        ),
    ]
