# Generated by Django 6.0 on 2026-01-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_original_ksic_code'),
        ('industries', '0003_populate_kis_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['market', '-created_at'], name='company_market_176689_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_deleted', '-updated_at'], name='company_is_dele_df16c5_idx'),
        ),
    ]
