# Generated by Django 6.0.1 on 2026-01-16 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='report',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='revenuecomposition',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='revenue_compositions', to='companies.company'),
        ),
    ]
