# Generated by Django 6.0 on 2026-01-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_add_company_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='pbr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='시가총액 ÷ 순자산 (순자산 = 총자산 - 총부채)', max_digits=10, null=True, verbose_name='PBR (주가순자산비율)'),
        ),
    ]
