# Generated by Django 6.0.1 on 2026-01-20 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SankeyFinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('revenue', models.BigIntegerField(default=0, verbose_name='총매출')),
                ('cost_of_sales', models.BigIntegerField(default=0, verbose_name='매출원가')),
                ('sg_and_a', models.BigIntegerField(default=0, verbose_name='판관비')),
                ('net_income', models.BigIntegerField(default=0, verbose_name='당기순이익')),
                ('segment_json', models.JSONField(blank=True, null=True, verbose_name='부문별 매출 데이터')),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sankey_data', to='companies.company')),
            ],
            options={
                'db_table': 'sankey_financial_data',
                'unique_together': {('company', 'year')},
            },
        ),
    ]
