# Generated by Django 6.0.1 on 2026-01-17 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_alter_financialstatement_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_revenue', models.BigIntegerField(default=0)),
                ('source_top1_name', models.CharField(max_length=255)),
                ('source_top1_val', models.BigIntegerField(default=0)),
                ('source_top2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_top2_val', models.BigIntegerField(default=0)),
                ('source_top3_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_top3_val', models.BigIntegerField(default=0)),
                ('source_others_val', models.BigIntegerField(default=0)),
                ('net_loss_val', models.BigIntegerField(default=0)),
                ('cost_of_sales', models.BigIntegerField(default=0)),
                ('sg_and_a', models.BigIntegerField(default=0)),
                ('tax_and_interest', models.BigIntegerField(default=0)),
                ('expense_others_val', models.BigIntegerField(default=0)),
                ('net_income_val', models.BigIntegerField(default=0)),
                ('company', models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, related_name='financial_flows', to='companies.company')),
            ],
            options={
                'db_table': 'financial_flow',
                'unique_together': {('company', 'year')},
            },
        ),
    ]
