# Generated by Django 6.0.1 on 2026-01-17 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_financialstatement_company_and_more'),
        ('sankeys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialflow',
            name='expense_others_val',
        ),
        migrations.RemoveField(
            model_name='financialflow',
            name='source_others_val',
        ),
        migrations.RemoveField(
            model_name='financialflow',
            name='source_top1_name',
        ),
        migrations.RemoveField(
            model_name='financialflow',
            name='source_top1_val',
        ),
        migrations.RemoveField(
            model_name='financialflow',
            name='source_top2_name',
        ),
        migrations.RemoveField(
            model_name='financialflow',
            name='source_top2_val',
        ),
        migrations.RemoveField(
            model_name='financialflow',
            name='source_top3_name',
        ),
        migrations.RemoveField(
            model_name='financialflow',
            name='source_top3_val',
        ),
        migrations.RemoveField(
            model_name='financialflow',
            name='tax_and_interest',
        ),
        migrations.AddField(
            model_name='financialflow',
            name='finance_costs',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='financialflow',
            name='source_etc_val',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='financialflow',
            name='source_fin_val',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='financialflow',
            name='source_oth_val',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='financialflow',
            name='source_rev_val',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='financialflow',
            name='tax_costs',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='financialflow',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='financialflow',
            name='cost_of_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='financialflow',
            name='net_income_val',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='financialflow',
            name='net_loss_val',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='financialflow',
            name='sg_and_a',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='financialflow',
            name='total_revenue',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterModelTable(
            name='financialflow',
            table=None,
        ),
    ]
