# Generated by Django 6.0.1 on 2026-01-20 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('sankeys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SankeyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('nodes', models.JSONField(default=list)),
                ('links', models.JSONField(default=list)),
                ('is_loss', models.BooleanField(default=False)),
                ('raw_values', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sankey_data', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'fiscal_year')},
            },
        ),
        migrations.DeleteModel(
            name='SankeyFinancialData',
        ),
    ]
