# Generated by Django 6.0.1 on 2026-01-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('index_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('market_type', models.CharField(max_length=10)),
                ('idx_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('volume', models.BigIntegerField(help_text='거래량 (주)')),
                ('amount', models.BigIntegerField(help_text='거래대금 (원)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'market_index',
                'ordering': ['-idx_date'],
                'unique_together': {('idx_date', 'market_type')},
            },
        ),
    ]
